"""add subscription_ends_at to users

Revision ID: 96d75e3b390e
Revises: eb7e6aad61ff
Create Date: 2026-06-10 10:29:13.619057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d75e3b390e'
down_revision: Union[str, Sequence[str], None] = 'eb7e6aad61ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_ends_at')
    # ### end Alembic commands ###
