"""add companies roles and user company fields

Revision ID: d10102a0960d
Revises: c4e130badf87
Create Date: 2026-06-11 12:00:13.959420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10102a0960d'
down_revision: Union[str, Sequence[str], None] = 'c4e130badf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rif', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('modules_enabled', sa.Text(), nullable=False),
    sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_owner_user_id', 'companies', ['owner_user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_roles_company_name')
    )
    op.create_index(op.f('ix_roles_company_id'), 'roles', ['company_id'], unique=False)
    op.add_column('users', sa.Column('company_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('module_access', sa.Text(), nullable=True))

    # Populate companies from existing users where owner_id = id
    op.execute("""
        INSERT INTO companies (id, owner_user_id, name, plan, modules_enabled, created_at)
        SELECT id, id, name, 'free', '["operativo"]', CURRENT_TIMESTAMP
        FROM users
        WHERE owner_id = id
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'module_access')
    op.drop_column('users', 'company_id')
    op.drop_index(op.f('ix_roles_company_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_companies_owner_user_id', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
